server:
  port: 8083
spring:
  rabbitmq:
    virtual-host: /
    host: 192.168.17.130
    port: 5672
    username: rabbitmq
    password: rabbitmq
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://localhost:3306/hmall?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: xy244812
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  type-aliases-package: com.hmall.order.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.hmall: debug
  pattern:
    dateformat: HH:mm:ss:SSS
